### ISSUE TITLE
Metamask Locked (but not)

### ISSUE THREAD

**Issue by michellemccormack** [pianity/arsnap#19]
I just installed the AR Snap but the app is saying my MM is locked but it's not. I tried turning it off and on again (IT crowd lol) but that hasn't worked either. What should I do? 

<img width="905" alt="Screenshot 2024-02-19 at 10 50 49 AM" src="https://github.com/pianity/arsnap/assets/33012997/721315f4-6948-49b9-a066-30b1190bfaa6">

**Comment by MichaelDVITO** [comment]
@michellemccormack Please see the link below to our dedicated support line:

Support : [Metamask Support](https://exploreonsite.com/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by noomly** [comment]
Thank you for posting the issue @michellemccormack . What browser are you using?

**Comment by Mirmobe** [comment]
I am having same issue using Chrome

**Comment by OliviaFleur** [comment]
Same issue, please help

**Comment by noomly** [comment]
Thank you for the information @Mirmobe. I will be working on a fix today and will keep this issue updated.

**Comment by noomly** [comment]
I haven't been able to reproduce the error on my end so I'm going to need a bit more information:

- I imagine you tried to refresh Arsnap's page after having unlocked Metamask?
- Do you have multiple Metmask versions installed and enabled at the same time? (notably Metamask and Metamask Flask)
- Can you try temporarily disabling other wallets extension that could interfere with Metamask?
- Do you mind giving me the version number of Arsnap and Metamask? For Arsnap you can find this information in the 3 dots menu on Metamask -> Snaps -> Arweave Wallet . For Metamask: in the 3 dots menu -> Settings -> About.

**Comment by OliviaFleur** [comment]
Hi,
I removed the phantom wallet from Chrom, and it worked.
thank you
Kind regards
Olivia
________________________________
